### PR TITLE
New archiso

### PR DESCRIPTION
**Pull request by sharkwouter**
This fixes is the new Archiso. The end result should be almost the same, but it still needs some testing.

### CODE REVIEW

**Comment by alkazar** [comment]
Really nice job!

I tested by installing to a VM in BIOS mode. Worked fine.

A few things:
 - the ISO is a lot larger now at nearly 800 MB; would be nice if we could get it down
 - I think we could do something different for frzr; maybe we can just include the frzr scripts directly in airootfs
 - the docker build is broken, I applied this change:
 ```
-exec docker run --privileged --rm -ti -v ${work_dir}/${output_dir}:/root/gameros/out -h gameros-builder gameros-builder ./build.sh -v
+exec docker run --privileged --rm -ti -v ${work_dir}:/root/gameros -h gameros-builder gameros-builder ./build-iso.sh
```
however, I get this error:
`/root/gameros/gameros/profiledef.sh: line 24: /etc/shadow: syntax error: operand expected (error token is "/etc/shadow")`
which doesn't really make sense.

**Comment by sharkwouter** [comment]
Yeah, the size difference is fixable. I'm adding a lot of extra stuff to the repository. What I would recommend we do is set up a pacman repository for frzr and add it and install it from there. I have a concept for how to do that here: https://github.com/sharkwouter/arch-repo-test

**Comment by sharkwouter** [comment]
With the last commit the resulting ISO is 631 MB. Is that acceptable? I had to keep ``base`` in there to make it not fail to build. It would probably be possible to do without and save another 100 MB, but I'm not sure what package is missing.

**Comment by sharkwouter** [comment]
Could you test the docker build again? For me it isn't working

**Comment by alkazar** [comment]
The docker build is still busted, but the ISO is now down to 600 MB which is great.
I built and tested a new ISO and it seems to work.

**Comment by alkazar** [comment]
I'll merge this for now I guess, thanks!

**Comment by sharkwouter** [comment]
Cool, I'll see if I can fix the docker build later then. Not sure what's up with it.

**Pull request merged**
